### ISSUE TITLE
Site logo does not link to home page

### ISSUE THREAD

**Issue by appleJax** [sandiegojs/sdjs-speaker-pipeline#100]
The main SanDiegoJS logo should link to the home page

![Screen Shot 2019-04-09 at 6 45 09 PM](https://user-images.githubusercontent.com/13618860/55846027-14924e80-5af9-11e9-89be-9b43d564a8c2.png)

**Comment by sqwisha** [comment]
working on this issues currently

**Comment by alishaevn** [comment]
This appears to be the same issue as https://github.com/sandiegojs/sdjs-speaker-pipeline/issues/112, which was resolved per this comment: https://github.com/sandiegojs/sdjs-speaker-pipeline/issues/112#issuecomment-501555684.

**Comment by keizax** [comment]
These issues are now resolved. Thank you for your contribution to SDJS.
