### ISSUE TITLE
"Shirts" link goes to blank page

### ISSUE THREAD

**Issue by huynhicode** [sandiegojs/sdjs-speaker-pipeline#101]
**Describe the bug**
Clicking on the "shirts" link in the nav bar opens up a blank page.

**To Reproduce**
1. Go to home page
2. Click on shirts link in the nav bar.

**Expected behavior**
For the "shirts" link to display a page re: shirts.

**Screenshots**

  1) take a screenshot 
      - Mac: shift + command + 3 
      - Windows: use desired screenshot program
 
  2) drag & drop screenshot image here:

<img width="836" alt="Screen Shot 2019-04-09 at 7 00 38 PM" src="https://user-images.githubusercontent.com/35910788/55846258-d77a8c00-5af9-11e9-9a95-b5ebd7100786.png">

**System Info (please complete the following information):**
 - Device: Macbook
 - OS: N/A
 - Browser: Chrome 
 - Version: [e.g. 22] 

**Additional context**

**Comment by mailelucks** [comment]
working on currently

**Comment by michaelerobertsjr** [comment]
Thank you for this contribution. It has been merged into the master branch.
