### ISSUE TITLE
Connect Page Does not Load

### ISSUE THREAD

**Issue by ch3rr17** [sandiegojs/sdjs-speaker-pipeline#102]
**Describe the bug**
 Consoles the following error:
Failed to load resource: the server responded with a status of 401 (Unauthorized)
createError.js:16 Uncaught (in promise) Error: Request failed with status code 401
    at e.exports (createError.js:16)
    at e.exports (settle.js:18)
    at XMLHttpRequest.m.(/anonymous function) (https://sdjs-speaker-pipeline-app.herokuapp.com/bundle.js:6:2169)

**To Reproduce**
1. Go to 'https://sdjs-speaker-pipeline-app.herokuapp.com/'
2. Click on 'Click on Connect'
3. Open Developer Tools and you'll see the error

**Expected behavior**
Unknown

**Screenshots**

  1) take a screenshot 
      - Screenshot: https://screencast.com/t/rsC9RBrRU
      - 
 
 

   
**System Info (please complete the following information):**
 - Device: Macbook Pro
 - OS: Yosemite
 - Browser: Chrome
 - Version: Version 73

**Additional context**

**Comment by michaelerobertsjr** [comment]
In this case I think we want to redirect users to [https://www.sandiegojs.org/connect](https://www.sandiegojs.org/connect)

**Comment by GianFiyah** [comment]
I am working on this.

**Comment by michaelerobertsjr** [comment]
Thank you for this contribution. It has been merged into the master branch.
