### ISSUE TITLE
Connect nav link broken

### ISSUE THREAD

**Issue by iprincess** [sandiegojs/sdjs-speaker-pipeline#103]
**Describe the bug**
 Clicking on the Connect link in the top nav takes the user to a blank screen.

**To Reproduce**
1. Go to the Speaker Pipeline home page
2. Click on the 'CONNECT' link in the top nav.
3. You will be taken to https://sdjs-speaker-pipeline-app.herokuapp.com/#/Connect
4. See blank page

**Expected behavior**
The 'Connect' page should show

**Screenshots**

   
**System Info (please complete the following information):**
 - Device: Macbook Pro,
 - OS: Mojave
 - Browser: Safari
 - Version: 

**Additional context**

**Comment by BladeSe7en** [comment]
This issue is resolved.

**Comment by michaelerobertsjr** [comment]
Thank you for this contribution. It has been merged into the master branch.
