### ISSUE TITLE
Speaker Registration Form Submit Returns 500 Error Code

### ISSUE THREAD

**Issue by mailelucks** [sandiegojs/sdjs-speaker-pipeline#105]
On submit of form, console returns "Uncaught (in promise) Error: Request failed with status code 500". Form should submit, preferably through AJAX with dynamic error and success messages (no refreshing of the page). Confirmation email might be nice as well, for record of submission.

**Comment by BladeSe7en** [comment]
The problem was happening because you did not have a local instance of mongo running. There is no actual error in the code. This ticket can be closed
