### ISSUE TITLE
No "Learn" page

### ISSUE THREAD

**Issue by nataliesun** [sandiegojs/sdjs-speaker-pipeline#106]
**Describe the bug**
Clicking the "Learn" on nav goes to a blank page

**To Reproduce**
1. Go to '.http://localhost:3000/#/.'
2. Click on 'LEARN'

**Expected behavior**
Should have a UI for content of LEARN

**Screenshots**

  1) take a screenshot 
      - Mac: shift + command + 3 
      - Windows: use desired screenshot program
 
  2) drag & drop screenshot image here:

   
**System Info (please complete the following information):**
 - Device: [e.g. Macbook Pro, iPhone6]
 - OS: [e.g. iOS, Android]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by joannawheeler** [comment]
@natsun121 I see. You were making two issues for JOBS and LEARN. I think the JOBS one needs to be edited as it says LEARN within the description.

**Comment by BladeSe7en** [comment]
This issue is solved and is apart of pull request #150

**Comment by michaelerobertsjr** [comment]
Thank you for this contribution. It has been merged into the master branch.
