### ISSUE TITLE
No "Jobs" page

### ISSUE THREAD

**Issue by nataliesun** [sandiegojs/sdjs-speaker-pipeline#107]
**Describe the bug**
Clicking on "JOBS" in the nav goes to a blank page

**To Reproduce**
1. Go to http://localhost:3000/#
2. Click on "LEARN"

**Expected behavior**
Should show UI for whatever content is on jobs page.
<img width="1249" alt="Screen Shot 2019-04-09 at 7 12 39 PM" src="https://user-images.githubusercontent.com/44484964/55846706-866b9780-5afb-11e9-86e7-39cc6151b49f.png">

**Screenshots**

  1) take a screenshot 
      - Mac: shift + command + 3 
      - Windows: use desired screenshot program
 
  2) drag & drop screenshot image here:

   
**System Info (please complete the following information):**
 - Device: [e.g. Macbook Pro, iPhone6]
 - OS: [e.g. iOS, Android]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by joannawheeler** [comment]
@natsun121 did you mean the LEARN page is not loading?

**Comment by nataliesun** [comment]
Yeah sorry! I'll just delete this one since Austene opened another issue about the same thing :)
