### ISSUE TITLE
No Job page

### ISSUE THREAD

**Issue by austene** [sandiegojs/sdjs-speaker-pipeline#108]
**Describe the bug**
There is no Job page when you click on "Job" in the top right corner.

**To Reproduce**
1. Go to landing page
2. Click on 'Job' tab in upper right corner.
3. See error

**Expected behavior**
I expected to land on the 'Jobs' page

**Comment by BladeSe7en** [comment]
This issue is solved and is apart of pull request #150

**Comment by michaelerobertsjr** [comment]
Thank you for this contribution. It has been merged into the master branch.
