### ISSUE TITLE
Footer with Code of Conduct link

### ISSUE THREAD

**Issue by huynhicode** [sandiegojs/sdjs-speaker-pipeline#111]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A footer with Code of Conduct.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by SanDiegoEMG** [comment]
Working on this!

**Comment by BladeSe7en** [comment]
this ticket is complete. Pull request #150

**Comment by michaelerobertsjr** [comment]
Thank you for this contribution. It has been merged into the master branch.
