### ISSUE TITLE
Clicking on SDJS logo doesn't work

### ISSUE THREAD

**Issue by nataliesun** [sandiegojs/sdjs-speaker-pipeline#112]
**Describe the bug**
Clicking on the SDJS logo on any page doesn't do anything.

**To Reproduce**
1. Go to any page
2. Click on SDJS logo in the top left corner
3. Nothing happens

**Expected behavior**
Should redirect to the home page.

**Screenshots**

  1) take a screenshot 
      - Mac: shift + command + 3 
      - Windows: use desired screenshot program
 
  2) drag & drop screenshot image here:

   
**System Info (please complete the following information):**
 - Device: [e.g. Macbook Pro, iPhone6]
 - OS: [e.g. iOS, Android]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by BladeSe7en** [comment]
this issue is resolved with pull request #142

**Comment by keizax** [comment]
These issues are now resolved. Thank you for your contribution to SDJS.
