### ISSUE TITLE
Tagline on organizers form is confusing

### ISSUE THREAD

**Issue by SanDiegoEMG** [sandiegojs/sdjs-speaker-pipeline#114]
**Describe the bug**
current tagline "Add Other Admins Contact Info" is confusing.

**To Reproduce**
1. Login as Admin
2. Click on 'Organizers'
3. Tagline is front and center

**Expected behavior**
Recommend to change to  "Create New Admin Account"

   
**System Info (please complete the following information):**
 - Device: MacBook Pro
 - OS: iOS
 - Browser: Chrome
 - Version: Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by Rush0415** [comment]
This issue is now resolved and will be merged to master. Thank you for your contribution to SDJS-speaker-pipeline.
