### ISSUE TITLE
Privacy Policy Needed

### ISSUE THREAD

**Issue by michaelerobertsjr** [sandiegojs/sdjs-speaker-pipeline#115]
**Is your feature request related to a problem? Please describe.**
All sites that collect PII need to have a privacy policy.

**Describe the solution you'd like**
The page should say what will be done with information that is entered.

**Comment by BladeSe7en** [comment]
this ticket is complete. Pull request #150

**Comment by michaelerobertsjr** [comment]
Thank you for this contribution. It has been merged into the master branch.
