### ISSUE TITLE
"Accounts" tab isn't working

### ISSUE THREAD

**Issue by abigailsy1** [sandiegojs/sdjs-speaker-pipeline#116]
**Describe the bug**
Clicking the "Accounts" tab leads you to a blank page. 

**To Reproduce**

**Expected behavior**
(Replace this line with a clear and concise description of what you expected to happen.)

**Screenshots**

  1) take a screenshot 
      - Mac: shift + command + 3 
      - Windows: use desired screenshot program
 
  2) drag & drop screenshot image here:

   
**System Info (please complete the following information):**
 - Device: [e.g. Macbook Pro, iPhone6]
 - OS: [e.g. iOS, Android]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by BladeSe7en** [comment]
This issue is resolved with pull request #149

**Comment by michaelerobertsjr** [comment]
Thanks for helping out, we have incorporated your changes into another pull request.
