### ISSUE TITLE
Organizers form submit button

### ISSUE THREAD

**Issue by SanDiegoEMG** [sandiegojs/sdjs-speaker-pipeline#118]
**Describe the bug**
Cursor doesn't change upon hover over the submit button

**To Reproduce**https://github.com/sandiegojs/sdjs-speaker-pipeline/issues/105
1. Login as Admin
2. Navigate to Organizers page
3. Submit button

**Expected behavior**
mouse change to a pointy finger upon hover and button can highlight 

   
**System Info (please complete the following information):**
 - Device: Macbook Pro
 - OS:  iOS
 - Browser:  Chrome 
 - Version: Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by keizax** [comment]
Thanks for helping out, we have incorporated your changes into another pull request.
