### ISSUE TITLE
Do & Do Not List Aesthietics

### ISSUE THREAD

**Issue by nataliesun** [sandiegojs/sdjs-speaker-pipeline#119]
**Is your feature request related to a problem? Please describe.**
The Do and Do not lists look out of place.

**Describe the solution you'd like**
Could use space and color better, it's squished. The shadows look odd. 

**Describe alternatives you've considered**
More space for bullet points. 
Color should match theme. 
Do and Do not needs to be centered. 
Responsive

**Additional context**

**Comment by keizax** [comment]
This issue has been resolved. Thank you for your contribution to SDJS.

**Comment by michaelerobertsjr** [comment]
Thanks for helping out, we have incorporated your changes into another pull request.
