### ISSUE TITLE
Must refresh the admin page after logging in to show content

### ISSUE THREAD

**Issue by iprincess** [sandiegojs/sdjs-speaker-pipeline#120]
**Describe the bug**
After logging in on the admin page, I have to refresh the page to see any content.

**To Reproduce**
1. Go to https://sdjs-speaker-pipeline-app.herokuapp.com/#/Admin/Login
2. Login with admin/test 
3. See the blank page (unsure what the url has at this point)
4. Refresh the page
5. http://localhost:3000/#/Admin/Meetups shows and the meetups appear

**Expected behavior**
After login you should be redirected to the meetups page automatically

**Screenshots**

  1) take a screenshot 
      - Mac: shift + command + 3 
      - Windows: use desired screenshot program
 
  2) drag & drop screenshot image here:

   
**System Info (please complete the following information):**
 - Device: MacBook Pro
 - OS: Mojave
 - Browser: Safari
 - Version: [e.g. 22]

**Additional context**

**Comment by GianFiyah** [comment]
## Bug Fixed
Run:
```npm start```

**Comment by michaelerobertsjr** [comment]
Thanks for your contribution.
