### ISSUE TITLE
Typos on homepage

### ISSUE THREAD

**Issue by huynhicode** [sandiegojs/sdjs-speaker-pipeline#121]
**Describe the bug**
Some typo correction suggestions:

Current: "We do accept extended talks but prefer presentors to have done a lightning talk before. If you're unsure please email us to discuss your talk."

Suggestion: "We do accept extended talks, but prefer presentors to have done a lightning talk before. If you're unsure, please email us to discuss your talk.

Comma between "talks" & "but".
Comma between "unsure" and "please".

Current: "presentors"
Suggestion: "presenters"

**Screenshots**

<img width="750" alt="Screen Shot 2019-04-09 at 7 27 50 PM" src="https://user-images.githubusercontent.com/35910788/55847325-b1ef8180-5afd-11e9-8f59-25d5d5ff49e9.png">

**Comment by hollyhaho** [comment]
Working on it

**Comment by MrExpert** [comment]
Thank you for your contribution to San Diego JS.

**Comment by michaelerobertsjr** [comment]
Thanks for helping out, we have incorporated your changes into another pull request.
