### ISSUE TITLE
Admin > Organizers > "Submit" not re-rendering

### ISSUE THREAD

**Issue by sqwisha** [sandiegojs/sdjs-speaker-pipeline#122]
**Description**
Path: Admin > Organizers > "Add Other Admins Contact Info" Form

Clicking **Submit** button does not trigger render. 
- Input fields do not clear
- "Current Organizers" table does not refresh

**To Reproduce**
1. Go to Admin (must be logged in)
2. Go to Organizers
3. Fill out input fields
4. Click "Submit"

**Expected behavior**
"Current Organizers" should refresh/re-render
Input fields should clear
   
**System Info:**
 - Device: MacBook Pro
 - OS: Mojave 10.14.3
 - Browser: Chrome 
 - Version: 73.0.3683.86 

**Additional context**
"Current Organizers" table refreshes, and input fields refresh when browser is refreshed.

**Comment by keizax** [comment]
Thanks for helping out, we have incorporated your changes into another pull request.
