### ISSUE TITLE
Adding organizer doesn't add new organizer to current organizers list

### ISSUE THREAD

**Issue by iprincess** [sandiegojs/sdjs-speaker-pipeline#124]
**Describe the bug**
After adding an organizer, you have to refresh the page before the new organizer appears in the organizer list.

**To Reproduce**
1. Go to /#/Organizers
2. Add an organizer
3. Scroll down to the bottom of the page
4. See that the new organizer is not there
5. See that there was a 500 error for /api/organizers (see screenshot)
6. Refresh the page, and see the new organizer is now there

**Expected behavior**
When a new organizer is successfully added, it should show in the organizer list with a page refresh

**Screenshots**
<img width="800" alt="image" src="https://user-images.githubusercontent.com/4593309/55847531-8caf4300-5afe-11e9-85b4-de9c7ba81d8d.png">

<img width="886" alt="image" src="https://user-images.githubusercontent.com/4593309/55847710-30005800-5aff-11e9-80d4-b36ea5ae2be4.png">

   
**System Info (please complete the following information):**
 - Device: MacBook Pro
 - OS: Mojave
 - Browser: Safari
 - Version: [e.g. 22]

**Additional context**

**Comment by BladeSe7en** [comment]
This is not an issue with the code. If you add an admin it works properly. The reason you are getting a 500 error is because you do not have the .env token for the sendgrid emailer. So when you add a new organizer, you are unauthorized to send the email.

**Comment by Rush0415** [comment]
This issue is now resolved and have been merged. Thank you for your contribution to SDJS-speaker-pipeline.

**Comment by keizax** [comment]
Thanks for helping out, we have incorporated your changes into another pull request.
