### ISSUE TITLE
Organizers form add field

### ISSUE THREAD

**Issue by SanDiegoEMG** [sandiegojs/sdjs-speaker-pipeline#125]
**Describe the bug**
user doesn't know which field they are using as a username

**To Reproduce**
1. Login as admin
2. Navigate to Organizers

**Expected behavior**
Replace 'Name' with "Username"

   
System Info (please complete the following information):

Device: Macbook Pro
OS: iOS
Browser: Chrome
Version: Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by hollyhaho** [comment]
Currently working on this

**Comment by michaelerobertsjr** [comment]
Thanks for your contribution.
