### ISSUE TITLE
Font Kerning (Spacing)

### ISSUE THREAD

**Issue by huynhicode** [sandiegojs/sdjs-speaker-pipeline#126]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Kerning adjustment to font.  Characters are too close together.

**Describe alternatives you've considered**
N/A

**Additional context**

<img width="721" alt="Screen Shot 2019-04-09 at 7 39 52 PM" src="https://user-images.githubusercontent.com/35910788/55847736-46a6af00-5aff-11e9-8205-45aeadd41f2e.png">

**Comment by aerze** [comment]
The kerning is just based on the font, though we could consider using another font-face if this one is illegible.
