### ISSUE TITLE
Organizers list add a confirm to the delete

### ISSUE THREAD

**Issue by SanDiegoEMG** [sandiegojs/sdjs-speaker-pipeline#131]
**Is your feature request related to a problem? Please describe.**
If someone hits the delete button, the action is executed immediate and there is no safety

**Describe the solution you'd like**
When the delete is clicked - make them a confirm the action

**Describe alternatives you've considered**
alert? modal?

**Comment by alishaevn** [comment]
Taking this issue.

**Comment by alishaevn** [comment]
PR: https://github.com/sandiegojs/sdjs-speaker-pipeline/pull/159

**Comment by michaelerobertsjr** [comment]
Thanks for helping out, we have incorporated your changes into another pull request.
