### ISSUE TITLE
Banner - Get Started Button 

### ISSUE THREAD

**Issue by huynhicode** [sandiegojs/sdjs-speaker-pipeline#132]
**Describe the bug**
Hovering over the "get started" button in the banner does not change the cursor from an arrow to a hand.  Hovering beneath the "get started button" DOES change the cursor from an arrow to a hand.

**Expected behavior**
Hovering over the "get started" button should change the cursor from an arrow to a hand.

**Screenshots**

<img width="205" alt="Screen Shot 2019-04-09 at 8 03 14 PM" src="https://user-images.githubusercontent.com/35910788/55848656-8a4ee800-5b02-11e9-9cda-ced5dc70efbe.png">

**System Info (please complete the following information):**
 - Device: Macbook
 - Browser: Chrome

**Comment by BladeSe7en** [comment]
this ticket is complete.

**Comment by michaelerobertsjr** [comment]
Thank you for this contribution. It has been merged into the master branch.
